### ISSUE TITLE
Error 8.0

### ISSUE THREAD

**Issue by Az0na** [Phanx/ClassColors#11]
Message: ...erface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:355: attempt to index global 'ChatConfigChatSettingsClassColorLegend' (a nil value)
Time: Wed Jul 18 23:13:04 2018
Count: 1
Stack: ...erface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:355: attempt to index global 'ChatConfigChatSettingsClassColorLegend' (a nil value)
...erface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:355: in main chunk

Locals: _ = "!ClassColorsBlizz"
ns = <table> {
}
strfind = <function> defined =[C]:-1
format = <function> defined =[C]:-1
gsub = <function> defined =[C]:-1
strmatch = <function> defined =[C]:-1
strsub = <function> defined =[C]:-1
pairs = <function> defined =[C]:-1
type = <function> defined =[C]:-1
addonFuncs = <table> {
 Blizzard_Calendar = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:33
 Blizzard_Collections = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:131
 Blizzard_TradeSkillUI = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:320
 Blizzard_GuildUI = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:204
 Blizzard_InspectUI = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:218
 Blizzard_RaidUI = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:252
 Blizzard_Commentator = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:162
 Blizzard_ChallengesUI = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:79
}
blizzHexColors = <table> {
 ffc41e3a = "DEATHKNIGHT"
 ffc69b6d = "WARRIOR"
 ff3fc6ea = "MAGE"
 ffff7c0a = "DRUID"
 ff8787ed = "WARLOCK"
 ffffffff = "PRIEST"
 ffa330c9 = "DEMONHUNTER"
 fffff468 = "ROGUE"
 ff0070dd = "SHAMAN"
 ff00ff96 = "MONK"
 ffaad372 = "HUNTER"
 fff48cba = "PALADIN"
}
ColorLegend = <function> defined @Interface\AddOns\!ClassColorsBlizz\ClassColorsBlizz.lua:348
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 colorStr = "fffff468"
 GetRGB = <function> defined @Interface\SharedXML\Util.lua:615
 OnLoad = <function> defined @Interface\SharedXML\Util.lua:604
 b = 0.41
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Util.lua:646
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Util.lua:650
 GenerateHexColor = <function> defined @Interface\SharedXML\Util.lua:642
 GetRGBA = <function> defined @Interface\SharedXML\Util.lua:623
 IsEqualTo = <function> defined @Interface\SharedXML\Util.lua:608
 g = 0.96
 r = 1
 SetRGBA = <function> defined @Interface\SharedXML\Util.lua:631
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Util.lua:619
 SetRGB = <function> defined @Interface\SharedXML\Util.lua:638
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Util.lua:627
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ChatConfigChatSettingsClassColorLegend' (a nil value)"

**Comment by Phanx** [comment]
Fixed in 8.0.0.0 release.
