### ISSUE TITLE
Recent lua errors...

### ISSUE THREAD

**Issue by ZaephirMoth** [Phanx/ClassColors#8]
Greetings !

  I've been using ClassColors for some time now, without any problems, up until very recently... I now encounter several lua errors each time I come in sight of any other player while friendly (custom class colored) nameplates are 'on'. See below for those errors, which of course stack each time any nameplate is crossed on screen... I don't play PvP much, so I can't tell if it would also affect enemy nameplates or not. Anyway, switching off all nameplates or using " /console ShowClassColorInFriendlyNameplate 0 " does solve that (minor) problem - 'minor', since it doesn't seem to affect much gameplay -, but testing "Class Colors" on any character, without any other addon, even on a fresh WTF (Cache, etc.) folder, doesn't change anything. So I'm left to suspect that a small recent patch change has broken Class Colors' habits...

  Thank you in advance for any help ! And thanks for your work anyway... Cheers !
  Benjamin

  Error 1), the most frequent one, which appears even without any other addon : 

Message: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
Time: 12/08/17 00:21:19
Count: 9
Stack: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
[C]: in function `SetStatusBarColor'
Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: in function <Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:100>
[C]: in function `CompactUnitFrame_UpdateHealthColor'
Interface\FrameXML\CompactUnitFrame.lua:287: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:174: in function `CompactUnitFrame_SetUnit'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:342: in function `OnAdded'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:86: in function `OnNamePlateAdded'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:44: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:35>

Locals: 

  Error 2) : 

Message: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
Time: 12/08/17 00:23:57
Count: 1
Stack: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
[C]: in function `SetStatusBarColor'
Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: in function <Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:100>
[C]: in function `CompactUnitFrame_UpdateHealthColor'
Interface\FrameXML\CompactUnitFrame.lua:95: in function <Interface\FrameXML\CompactUnitFrame.lua:53>

Locals: 

  Error 3) : 

Message: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
Time: 12/08/17 00:32:45
Count: 1
Stack: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
[C]: in function `SetStatusBarColor'
Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: in function <Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:100>
[C]: in function `CompactUnitFrame_UpdateHealthColor'
Interface\FrameXML\CompactUnitFrame.lua:287: in function <Interface\FrameXML\CompactUnitFrame.lua:281>
[C]: in function `CompactUnitFrame_UpdateAll'
Interface\FrameXML\CompactUnitFrame.lua:205: in function `CompactUnitFrame_SetUpFrame'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:108: in function `ApplyFrameOptions'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:323: in function `UpdateNamePlateOptions'
Interface\FrameXML\InterfaceOptionsPanels.lua:1324: in function `setFunc'
Interface\FrameXML\InterfaceOptionsPanels.lua:89: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:85>
[C]: in function `pcall'
Interface\FrameXML\InterfaceOptionsFrame.lua:217: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:216>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsFrame.lua:252: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:248>

Locals: 

  Error 4) :

Message: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
Time: 12/08/17 23:14:41
Count: 2
Stack: Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
[C]: in function `SetStatusBarColor'
Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:107: in function <Interface\AddOns\!ClassColors\ClassColorsBlizz.lua:100>
[C]: in function `CompactUnitFrame_UpdateHealthColor'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:186: in function `OnUnitFactionChanged'
...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:64: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:35>

Locals:

**Comment by ZaephirMoth** [comment]
After installing BugSack, here's an example of its reports. I say 'example', because they're all almost the same, but mention different class characters and color codes in the end. Strangely, from what I understand, it also involves the unfamous CompactUnitFrame (which I don't use, because I don't want anyone here to kill me ^^)...

262x !ClassColors\ClassColorsBlizz.lua:107: attempt to call method 'SetStatusBarColor' (a nil value)
!ClassColors\ClassColorsBlizz.lua:107: in function <!ClassColors\ClassColorsBlizz.lua:100>
[C]: in function `CompactUnitFrame_UpdateHealthColor'
FrameXML\CompactUnitFrame.lua:287: in function <FrameXML\CompactUnitFrame.lua:281>
[C]: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:174: in function `CompactUnitFrame_SetUnit'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:342: in function `OnAdded'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:86: in function `OnNamePlateAdded'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:44: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:35>

Locals:
frame = NamePlate11UnitFrame {
 0 = <userdata>
 name = <unnamed> {
 }
 selectionHighlight = <unnamed> {
 }
 otherHealPrediction = <unnamed> {
 }
 classificationIndicator = <unnamed> {
 }
 myHealAbsorbLeftShadow = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 unit = "nameplate11"
 unitExists = true
 maxDispelDebuffs = 0
 disableMouse = true
 inVehicle = false
 totalAbsorbOverlay = <unnamed> {
 }
 statusText = <unnamed> {
 }
 maxBuffs = 0
 maxDebuffs = 0
 RaidTargetFrame = <unnamed> {
 }
 castBar = <unnamed> {
 }
 healthBar = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 displayedUnit = "nameplate11"
 optionTable = <table> {
 }
 BuffFrame = <unnamed> {
 }
 LoseAggroAnim = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 hideCastbar = false
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 newUnit = true
}
_ = "Mage"
class = "MAGE"
color = <table> {
 b = 0.92
 colorStr = "ff3fc6ea"
 g = 0.78
 r = 0.25
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = 0.25
(*temporary) = 0.78
(*temporary) = 0.92
(*temporary) = "attempt to call method 'SetStatusBarColor' (a nil value)"
UnitIsConnected = <function> defined =[C]:-1
UnitIsPlayer = <function> defined =[C]:-1
UnitClass = <function> defined =[C]:-1

**Comment by Phanx** [comment]
This was fixed in 32545b9 (I think).
