### ISSUE TITLE
New Update Nice but spam in Gchat tab and FPS drops.

### ISSUE THREAD

**Issue by Az0na** [Phanx/ClassColors#9]
New update is nice, I see custom class colors blibs on world map actualy custom colors (minimap sadly not this is still blizzard class colors) how ever there is spam message in 1 of chat windows says.

GetUnitColor party1 PALADIN
GetUnitColor party1 PALADIN
GetUnitColor party1 PALADIN (for like 50 times, this was only with 1 party member)

![message](https://user-images.githubusercontent.com/30128793/37230011-44d73ea2-23e6-11e8-99ff-9256cc79e038.png)

this is on my shown on my Guid only chat windows not on any other window I use for chats.

says different classes depending on how many are in your group in pvp I had all different classes there.

I also think this causes huge FPS drops when in lage group ( I notice sins today that AV was exremly low FPS wich normal did not had)

Their is no LUA error  so gues something should not be like this?

**Comment by Az0na** [comment]
Just to get rid of message I edited window it used to windows I do not have still dunno if thats healthy it spams that much.

and ofcourse Minimap still use orignal colors, I hope you can get that to work as well its last straw I get annoyed by on my UI :)

**Comment by tordenflesk** [comment]
Same issue for me. "luckily" it's in a chatframe I rarely use, so it might have been an issue for a long time.

**Comment by Phanx** [comment]
Fixed the debug spam, release forthcoming.

Unfortunately there is no solution for the minimap icons. In past years it was possible by editing an image file and placing it at a specific location, but AFAIK this hasn't worked at least as far back as WoD.

@Az0na If you're still seeing FPS drops and can verify that the problem goes away when you disable the "Class Colors: Blizzard" module in your addons list, please open a new issue about that separate problem.
